### PR TITLE
Better handle ws errors

### PR DESCRIPTION
**Pull request by rmg**
Improves testability of WS channel as well as better handling of disconnects and unset acknowledgements.

Connect to strongloop-internal/scrum-nodeops#755

### CODE REVIEW

**Comment by rmg** [comment]
@piscisaureus does this cover the problem you are describing in #26?

Also, PTAL, I think this is ready for review.

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@piscisaureus the `connect` and `connection` are 2 different events for 2 different scenarios.

**Comment by piscisaureus** [comment]
> @piscisaureus the connect and connection are 2 different events for 2 different scenarios.

In any case the ws.once('open', emit) handler should be removed in `_detach()`, because it's possible that a socket is detached before it is connected and if that were to happen the internal state gets messed up.

Other than that, lgtm.

**Comment by rmg** [comment]
@slnode test please

**Pull request merged**
