### PR TITLE
upgrades ws to version > 1.1.0

### PR DESCRIPTION
**Pull request by bhajian**
connected to https://github.com/strongloop/strong-control-channel/issues/41

### CODE REVIEW

**Comment by sam-github** [comment]
@bhajian LGTM, but tests have to pass, and I think you should sign the CLA, for consistency.

**Comment by bhajian** [comment]
@slnode test please

**Comment by bhajian** [comment]
aa

**Comment by sam-github** [comment]
@slnode test please

**Comment by sam-github** [comment]
@rmg strong-executor build details is 404, and also, why is it even being checked? Its not in ci-infrastructure/projects.yml, but perhaps that isn't enough to cause it to not be considered a dependent?

**Comment by rmg** [comment]
@sam-github it existed when the build was run, 2 weeks ago.

**Comment by sam-github** [comment]
@slnode test please

**Pull request merged**
