### PR TITLE
replace express-ws with internal router

### PR DESCRIPTION
**Pull request by rmg**
Connect to #21
Connect to strongloop-internal/scrum-nodeops#582

### CODE REVIEW

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@sam-github @piscisaureus PTAL.

**Comment by piscisaureus** [comment]
@rmg LGTM

**Comment by rmg** [comment]
@piscisaureus made one other change, if you wouldn't mind taking another look

**Comment by piscisaureus** [comment]
@rmg It's not clear to me *why* that change is necessary or desirable, but the implementation LGTM, feel free to land.

**Comment by rmg** [comment]
@piscisaureus it allows future changes to the path to _not_ require a PR to both the client and server.

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
For posterity: the path to connect to should be determined by the server. The path change makes it easier to implement that, as in strongloop/strong-supervisor#135.

**Pull request merged**
